name: Footnotes
author: michael
category: Utilities
tags: [footnotes, print, citation, accessibility, a11y, usability]
current: 0.1
docs: 'http://github.com/michaelficarra/MooTools-Footnotes'
#demo: http://url.to.demo
